version: "3.9"

services:
  chat-server:
    build: ./server
    container_name: chat_server
    networks:
      - chatnet
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true

  client1:
    build: ./client
    container_name: client1
    networks:
      - chatnet
    depends_on:
      - chat-server
    stdin_open: true
    tty: true

  client2:
    build: ./client
    container_name: client2
    networks:
      - chatnet
    depends_on:
      - chat-server
    stdin_open: true
    tty: true

  client3:
    build: ./client
    container_name: client3
    networks:
      - chatnet
    depends_on:
      - chat-server
    stdin_open: true
    tty: true

networks:
  chatnet:
    driver: bridge
