version: "3.9"

services:
  server:
    build: ./server
    container_name: secure_chat_server
    networks:
      - chatnet

  client:
    build: ./client
    container_name: secure_chat_client
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
