version: "3.9"

services:
  chat-server:
    build: .
    container_name: chat_server
    command: tail -f /dev/null
    networks:
      chatnet:
        ipv4_address: 172.16.238.10
    ports:
      - "51262:51262"
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

  client1:
    build: .
    container_name: client1
    command: tail -f /dev/null
    networks:
      chatnet:
        ipv4_address: 172.16.238.11
    depends_on:
      - chat-server
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

  client2:
    build: .
    container_name: client2
    command: tail -f /dev/null
    networks:
      chatnet:
        ipv4_address: 172.16.238.12
    depends_on:
      - chat-server
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

  client3:
    build: .
    container_name: client3
    command: tail -f /dev/null
    networks:
      chatnet:
        ipv4_address: 172.16.238.13
    depends_on:
      - chat-server
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

networks:
  chatnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
